/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://xhmpyzdukbcjxojpngjpi3ttca.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2x2wmibkcncmnknzy6b32hwste",
    "aws_cognito_identity_pool_id": "ap-southeast-1:3a9951fc-4b4d-4523-8905-c88d8670870c",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_3oZ7QzPem",
    "aws_user_pools_web_client_id": "2kn4nmp5t4bqervuoq3700urhg",
    "oauth": {}
};


export default awsmobile;
